package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"bff-graphql-payment/graph/generated"
	"bff-graphql-payment/graph/model"
	gqlerrors "bff-graphql-payment/internal/infrastructure/inbound/graphql/errors"
	"bff-graphql-payment/internal/infrastructure/inbound/middleware"
	"context"
	"fmt"
	"log"
	"strconv"
	"time"

	"github.com/Odihnx/platform-core/tracing"
)

// GeneratePurchaseOrder is the resolver for the generatePurchaseOrder field.
func (r *mutationResolver) GeneratePurchaseOrder(ctx context.Context, input model.GeneratePurchaseOrderInput) (*model.GeneratePurchaseOrderResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.mutation.GeneratePurchaseOrder")
	defer span.End()

	hasCoupon := input.CouponCode != nil && *input.CouponCode != ""
	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type":  "mutation",
		"graphql.operation.name":  "generatePurchaseOrder",
		"input.rack_id_reference": strconv.Itoa(input.RackIDReference),
		"input.group_id":          strconv.Itoa(input.GroupID),
		"input.has_coupon":        strconv.FormatBool(hasCoupon),
		"input.trace_id":          input.TraceID,
		"input.gateway_name":      input.GatewayName,
	})

	// Normalizar couponCode: si es un puntero a string vacío, convertir a nil
	couponCode := input.CouponCode
	if couponCode != nil && *couponCode == "" {
		couponCode = nil
	}

	couponCodeLog := "nil"
	if couponCode != nil {
		couponCodeLog = fmt.Sprintf("%q", *couponCode)
	}
	log.Printf("RESOLVER [generatePurchaseOrder] >> recibido | rack=%d grupo=%d cupon=%s email=%s gateway=%s trace=%s",
		input.RackIDReference, input.GroupID, couponCodeLog, input.UserEmail, input.GatewayName, input.TraceID)

	// Llamar al caso de uso
	order, err := r.paymentInfraService.GeneratePurchaseOrder(ctx, input.RackIDReference, input.GroupID, couponCode, input.UserEmail, input.UserPhone, input.TraceID, input.GatewayName)
	if err != nil {
		log.Printf("RESOLVER [generatePurchaseOrder] ERROR | causa=%v | rack=%d grupo=%d trace=%s", err, input.RackIDReference, input.GroupID, input.TraceID)
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	log.Printf("RESOLVER [generatePurchaseOrder] << OK | rack=%d grupo=%d trace=%s", input.RackIDReference, input.GroupID, input.TraceID)
	// Mapear a respuesta GraphQL
	return r.mapper.ToPurchaseOrderResponse(order), nil
}

// GenerateBooking is the resolver for the generateBooking field.
func (r *mutationResolver) GenerateBooking(ctx context.Context, input model.GenerateBookingInput) (*model.GenerateBookingResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.mutation.GenerateBooking")
	defer span.End()

	hasCoupon := input.CouponCode != nil && *input.CouponCode != ""
	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type":  "mutation",
		"graphql.operation.name":  "generateBooking",
		"input.rack_id_reference": strconv.Itoa(input.RackIDReference),
		"input.group_id":          strconv.Itoa(input.GroupID),
		"input.has_coupon":        strconv.FormatBool(hasCoupon),
		"input.trace_id":          input.TraceID,
	})

	// Normalizar couponCode: si es un puntero a string vacío, convertir a nil
	couponCode := input.CouponCode
	if couponCode != nil && *couponCode == "" {
		couponCode = nil
	}

	// Llamar al caso de uso
	booking, err := r.paymentInfraService.GenerateBooking(ctx, input.RackIDReference, input.GroupID, couponCode, input.UserEmail, input.UserPhone, input.TraceID)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToBookingResponse(booking), nil
}

// GenerateCoupon is the resolver for the generateCoupon field.
func (r *mutationResolver) GenerateCoupon(ctx context.Context, input model.GenerateCouponInput) (*model.GenerateCouponResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.mutation.GenerateCoupon")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "mutation",
		"graphql.operation.name": "generateCoupon",
		"input.rack_id":          strconv.Itoa(input.RackID),
		"input.amount":           strconv.Itoa(input.Amount),
		"input.trace_id":         input.TraceID,
	})
	log.Printf("RESOLVER [generateCoupon] >> recibido | rack=%d monto=%d sizes=%v trace=%s", input.RackID, input.Amount, input.GroupIds, input.TraceID)

	// Llamar al caso de uso
	generation, err := r.paymentInfraService.GenerateCoupon(ctx, input.RackID, input.GroupIds, input.Amount, input.InitAt, input.FinishAt, input.TraceID)
	if err != nil {
		log.Printf("RESOLVER [generateCoupon] ERROR | causa=%v | rack=%d monto=%d trace=%s", err, input.RackID, input.Amount, input.TraceID)
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	log.Printf("RESOLVER [generateCoupon] << OK | codigo=%s | rack=%d trace=%s", generation.CouponCode, input.RackID, input.TraceID)
	// Mapear a respuesta GraphQL
	return r.mapper.ToGenerateCouponResponse(generation), nil
}

// CreateRackPayment is the resolver for the createRackPayment field.
func (r *mutationResolver) CreateRackPayment(ctx context.Context, input model.CreateRackPaymentInput) (*model.CreateRackPaymentResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.mutation.CreateRackPayment")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type":    "mutation",
		"graphql.operation.name":    "createRackPayment",
		"input.rack_reference":      strconv.Itoa(input.RackReference),
		"input.pricing_template_id": strconv.Itoa(input.PricingTemplateID),
		"input.booking_time_ids":    fmt.Sprintf("%v", input.BookingTimeIds),
	})

	result, err := r.paymentInfraService.CreateRackPayment(ctx, input.RackReference, input.PricingTemplateID, input.Notes, input.BookingTimeIds)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	return r.mapper.ToCreateRackPaymentResponse(result), nil
}

// GetPaymentInfraByQRValue is the resolver for the getPaymentInfraByQrValue field.
func (r *queryResolver) GetPaymentInfraByQRValue(ctx context.Context, input model.GetPaymentInfraByQRValueInput) (*model.PaymentInfraResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.query.GetPaymentInfraByQRValue")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "query",
		"graphql.operation.name": "getPaymentInfraByQrValue",
		"input.qr_value":         input.QRValue,
	})

	// Llamar al caso de uso
	paymentInfra, err := r.paymentInfraService.GetPaymentInfraByQrValue(ctx, input.QRValue)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToGraphQLResponse(paymentInfra), nil
}

// GetAvailableLockersByRackIDAndBookingTime is the resolver for the getAvailableLockersByRackIDAndBookingTime field.
func (r *queryResolver) GetAvailableLockersByRackIDAndBookingTime(ctx context.Context, input model.GetAvailableLockersByRackIDAndBookingTimeInput) (*model.AvailableLockersByRackIDAndBookingTimeResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.query.GetAvailableLockersByRackIDAndBookingTime")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "query",
		"graphql.operation.name": "getAvailableLockersByRackIDAndBookingTime",
		"input.payment_rack_id":  strconv.Itoa(input.PaymentRackID),
		"input.booking_time_id":  strconv.Itoa(input.BookingTimeID),
		"input.trace_id":         input.TraceID,
	})

	// Llamar al caso de uso
	lockers, err := r.paymentInfraService.GetAvailableLockers(ctx, input.PaymentRackID, input.BookingTimeID, input.TraceID)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToAvailableLockersByRackIDAndBookingTimeResponse(lockers), nil
}

// ValidateDiscountCoupon is the resolver for the validateDiscountCoupon field.
func (r *queryResolver) ValidateDiscountCoupon(ctx context.Context, input model.ValidateDiscountCouponInput) (*model.ValidateDiscountCouponResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.query.ValidateDiscountCoupon")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "query",
		"graphql.operation.name": "validateDiscountCoupon",
		"input.coupon_code":      input.CouponCode,
		"input.rack_id":          strconv.Itoa(input.RackID),
		"input.group_id":         strconv.Itoa(input.GroupID),
		"input.trace_id":         input.TraceID,
	})
	log.Printf("RESOLVER [validateDiscountCoupon] >> recibido | rack=%d cupon=%q grupo=%d trace=%s", input.RackID, input.CouponCode, input.GroupID, input.TraceID)

	// Llamar al caso de uso
	validation, err := r.paymentInfraService.ValidateDiscountCoupon(ctx, input.CouponCode, input.RackID, input.GroupID, input.TraceID)
	if err != nil {
		log.Printf("RESOLVER [validateDiscountCoupon] ERROR | causa=%v | rack=%d cupon=%q grupo=%d trace=%s", err, input.RackID, input.CouponCode, input.GroupID, input.TraceID)
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	log.Printf("RESOLVER [validateDiscountCoupon] << OK | aplica=%t tipo=%s monto=%d pct=%.2f | rack=%d cupon=%q grupo=%d trace=%s", validation.Applies, validation.DiscountType, validation.DiscountAmount, validation.DiscountPercentage, input.RackID, input.CouponCode, input.GroupID, input.TraceID)
	// Mapear a respuesta GraphQL
	return r.mapper.ToValidateCouponResponse(validation), nil
}

// GetPurchaseOrderByPo is the resolver for the getPurchaseOrderByPo field.
func (r *queryResolver) GetPurchaseOrderByPo(ctx context.Context, input model.GetPurchaseOrderByPoInput) (*model.PurchaseOrderResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.query.GetPurchaseOrderByPo")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "query",
		"graphql.operation.name": "getPurchaseOrderByPo",
		"input.purchase_order":   input.PurchaseOrder,
		"input.trace_id":         input.TraceID,
	})

	// Llamar al caso de uso
	orderData, err := r.paymentInfraService.GetPurchaseOrderByPo(ctx, input.PurchaseOrder, input.TraceID)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToPurchaseOrderDataResponse(orderData), nil
}

// CheckBookingStatus is the resolver for the checkBookingStatus field.
func (r *queryResolver) CheckBookingStatus(ctx context.Context, input model.CheckBookingStatusInput) (*model.CheckBookingStatusResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.query.CheckBookingStatus")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "query",
		"graphql.operation.name": "checkBookingStatus",
		"input.service_name":     input.ServiceName,
		"input.current_code":     input.CurrentCode,
	})

	// Llamar al caso de uso
	bookingStatus, err := r.paymentInfraService.CheckBookingStatus(ctx, input.ServiceName, input.CurrentCode)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToBookingStatusResponse(bookingStatus), nil
}

// GetBookingPayment is the resolver for the getBookingPayment field.
func (r *queryResolver) GetBookingPayment(ctx context.Context, input model.GetBookingPaymentInput) (*model.BookingPaymentResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.query.GetBookingPayment")
	defer span.End()

	attrs := map[string]string{
		"graphql.operation.type": "query",
		"graphql.operation.name": "getBookingPayment",
	}
	if input.DeviceID != nil {
		attrs["input.device_id"] = *input.DeviceID
	}
	if input.ActiveOnly != nil {
		attrs["input.active_only"] = strconv.FormatBool(*input.ActiveOnly)
	}
	if input.Page != nil {
		attrs["input.page"] = strconv.Itoa(*input.Page)
	}
	if input.PageSize != nil {
		attrs["input.page_size"] = strconv.Itoa(*input.PageSize)
	}
	if input.DateFrom != nil {
		attrs["input.date_from"] = *input.DateFrom
	}
	if input.DateUntil != nil {
		attrs["input.date_until"] = *input.DateUntil
	}
	if input.SortBy != nil {
		attrs["input.sort_by"] = *input.SortBy
	}
	tracing.AddAttributes(span, attrs)

	domainInput := r.mapper.ToGetBookingPaymentInput(input)

	claims, ok := middleware.GetUserClaims(ctx)
	if !ok {
		return nil, gqlerrors.New(ctx, fmt.Errorf("unauthorized: no authentication claims found"))
	}

	tracing.AddAttributes(span, map[string]string{"auth.user_email": claims.Email})

	if claims.HasRole("ADMIN") {
		installations, instErr := r.paymentInfraService.GetInstallationsByUserEmail(ctx, claims.Email)
		if instErr != nil {
			tracing.RecordError(span, instErr)
			return nil, gqlerrors.New(ctx, fmt.Errorf("failed to retrieve installations for user: %w", instErr))
		}
		domainInput.InstallationsName = installations
	} else if !claims.HasRole("SUPER_ADMIN") {
		return nil, gqlerrors.New(ctx, fmt.Errorf("forbidden: ADMIN or SUPER_ADMIN role required"))
	}

	history, err := r.paymentInfraService.GetBookingPayment(ctx, domainInput)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	return r.mapper.ToBookingPaymentResponse(history), nil
}

// GetPricingTemplates is the resolver for the getPricingTemplates field.
func (r *queryResolver) GetPricingTemplates(ctx context.Context) (*model.GetPricingTemplatesResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.query.GetPricingTemplates")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "query",
		"graphql.operation.name": "getPricingTemplates",
	})

	result, err := r.paymentInfraService.GetPricingTemplates(ctx)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	return r.mapper.ToPricingTemplatesResponse(result), nil
}

// GetBookingTimes is the resolver for the getBookingTimes field.
func (r *queryResolver) GetBookingTimes(ctx context.Context) (*model.GetBookingTimesResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.query.GetBookingTimes")
	defer span.End()

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "query",
		"graphql.operation.name": "getBookingTimes",
	})

	result, err := r.paymentInfraService.GetBookingTimes(ctx)
	if err != nil {
		tracing.RecordError(span, err)
		return nil, gqlerrors.New(ctx, err)
	}

	return r.mapper.ToBookingTimesResponse(result), nil
}

// ExecuteOpen is the resolver for the executeOpen field.
func (r *subscriptionResolver) ExecuteOpen(ctx context.Context, input model.ExecuteOpenInput) (<-chan *model.ExecuteOpenResponse, error) {
	ctx, span := tracing.StartSpan(ctx, "graphql.subscription.ExecuteOpen")

	tracing.AddAttributes(span, map[string]string{
		"graphql.operation.type": "subscription",
		"graphql.operation.name": "executeOpen",
		"input.service_name":     input.ServiceName,
		"input.current_code":     input.CurrentCode,
	})

	log.Printf("RESOLVER-SUB [executeOpen] >> recibido | servicio=%s code=%s", input.ServiceName, input.CurrentCode)

	// Obtener el canal del servicio que emite los 3 estados progresivamente
	domainChan, err := r.paymentInfraService.ExecuteOpenStream(ctx, input.ServiceName, input.CurrentCode)
	if err != nil {
		log.Printf("RESOLVER-SUB [executeOpen] ERROR no se pudo iniciar el stream | causa=%v | servicio=%s code=%s", err, input.ServiceName, input.CurrentCode)
		tracing.RecordError(span, err)
		span.End()
		return nil, gqlerrors.New(ctx, err)
	}

	// Crear canal de salida para GraphQL con buffer suficiente para los 3 mensajes
	outputChan := make(chan *model.ExecuteOpenResponse, 5)

	// Goroutine para transformar y reenviar los mensajes del dominio a GraphQL
	go func() {
		defer span.End()
		defer func() {
			log.Printf("RESOLVER-SUB [executeOpen] paso: cerrando canal de salida | servicio=%s code=%s", input.ServiceName, input.CurrentCode)
			close(outputChan)
		}()

		messageCount := 0
		var lastMessage *model.ExecuteOpenResponse

		for domainResult := range domainChan {
			messageCount++

			log.Printf("RESOLVER-SUB [executeOpen] paso: mensaje %d recibido del stream | openStatus=%v mensaje=%s code=%s",
				messageCount, domainResult.OpenStatus, domainResult.Message, input.CurrentCode)

			// Mapear de dominio a GraphQL
			graphQLResponse := r.mapper.ToExecuteOpenResponse(domainResult)
			lastMessage = graphQLResponse

			// Enviar al frontend de forma no bloqueante con timeout
			select {
			case outputChan <- graphQLResponse:
				log.Printf("RESOLVER-SUB [executeOpen] paso: mensaje %d enviado al frontend | status=%v code=%s",
					messageCount, graphQLResponse.OpenStatus, input.CurrentCode)
			case <-ctx.Done():
				log.Printf("RESOLVER-SUB [executeOpen] AVISO contexto cancelado tras %d mensajes | code=%s", messageCount, input.CurrentCode)
				return
			}

			// Log si es un estado terminal pero NO salimos, esperamos a que el canal se vacíe
			if domainResult.OpenStatus == "OPEN_STATUS_SUCCESS" || domainResult.OpenStatus == "OPEN_STATUS_ERROR" {
				log.Printf("RESOLVER-SUB [executeOpen] paso: estado terminal enviado (%v), esperando vaciar el canal | code=%s", domainResult.OpenStatus, input.CurrentCode)
			}
		}

		// El canal domainChan se cerró (ya se enviaron todos los mensajes)
		log.Printf("RESOLVER-SUB [executeOpen] << OK | completado con %d mensajes, ultimo status=%v | code=%s",
			messageCount, lastMessage.OpenStatus, input.CurrentCode)

		tracing.AddAttributes(span, map[string]string{
			"subscription.message_count": strconv.Itoa(messageCount),
			"subscription.final_status":  fmt.Sprintf("%v", lastMessage.OpenStatus),
		})

		// Pequeño delay para asegurar que el último mensaje se procese
		time.Sleep(100 * time.Millisecond)
	}()

	return outputChan, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
