package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"bff-graphql-payment/graph/generated"
	"bff-graphql-payment/graph/model"
	"context"
	"fmt"
	"time"
)

// GeneratePurchaseOrder is the resolver for the generatePurchaseOrder field.
func (r *mutationResolver) GeneratePurchaseOrder(ctx context.Context, input model.GeneratePurchaseOrderInput) (*model.GeneratePurchaseOrderResponse, error) {
	// Normalizar couponCode: si es un puntero a string vacío, convertir a nil
	couponCode := input.CouponCode
	if couponCode != nil && *couponCode == "" {
		couponCode = nil
	}

	// Log para debug
	couponCodeLog := "nil"
	if couponCode != nil {
		couponCodeLog = fmt.Sprintf("\"%s\"", *couponCode)
	}
	fmt.Printf("🔷 GraphQL Resolver - GeneratePurchaseOrder: rackId=%d, groupId=%d, couponCode=%s, email=%s, phone=%s, traceId=%s, gateway=%s\n",
		input.RackIDReference, input.GroupID, couponCodeLog, input.UserEmail, input.UserPhone, input.TraceID, input.GatewayName)

	// Llamar al caso de uso
	order, err := r.paymentInfraService.GeneratePurchaseOrder(ctx, input.RackIDReference, input.GroupID, couponCode, input.UserEmail, input.UserPhone, input.TraceID, input.GatewayName)
	if err != nil {
		fmt.Printf("❌ GraphQL Resolver - GeneratePurchaseOrder failed: %v\n", err)
		return nil, fmt.Errorf("failed to generate purchase order: %w", err)
	}

	fmt.Printf("✅ GraphQL Resolver - GeneratePurchaseOrder succeeded\n")
	// Mapear a respuesta GraphQL
	return r.mapper.ToPurchaseOrderResponse(order), nil
}

// GenerateBooking is the resolver for the generateBooking field.
func (r *mutationResolver) GenerateBooking(ctx context.Context, input model.GenerateBookingInput) (*model.GenerateBookingResponse, error) {
	// Normalizar couponCode: si es un puntero a string vacío, convertir a nil
	couponCode := input.CouponCode
	if couponCode != nil && *couponCode == "" {
		couponCode = nil
	}

	// Llamar al caso de uso
	booking, err := r.paymentInfraService.GenerateBooking(ctx, input.RackIDReference, input.GroupID, couponCode, input.UserEmail, input.UserPhone, input.TraceID)
	if err != nil {
		return nil, fmt.Errorf("failed to generate booking: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToBookingResponse(booking), nil
}

// GetPaymentInfraByQRValue is the resolver for the getPaymentInfraByQrValue field.
func (r *queryResolver) GetPaymentInfraByQRValue(ctx context.Context, input model.GetPaymentInfraByQRValueInput) (*model.PaymentInfraResponse, error) {
	// Llamar al caso de uso
	paymentInfra, err := r.paymentInfraService.GetPaymentInfraByQrValue(ctx, input.QRValue)
	if err != nil {
		return nil, fmt.Errorf("failed to get payment infrastructure: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToGraphQLResponse(paymentInfra), nil
}

// GetAvailableLockersByRackIDAndBookingTime is the resolver for the getAvailableLockersByRackIDAndBookingTime field.
func (r *queryResolver) GetAvailableLockersByRackIDAndBookingTime(ctx context.Context, input model.GetAvailableLockersByRackIDAndBookingTimeInput) (*model.AvailableLockersByRackIDAndBookingTimeResponse, error) {
	// Llamar al caso de uso
	lockers, err := r.paymentInfraService.GetAvailableLockers(ctx, input.PaymentRackID, input.BookingTimeID, input.TraceID)
	if err != nil {
		return nil, fmt.Errorf("failed to get available lockers: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToAvailableLockersByRackIDAndBookingTimeResponse(lockers), nil
}

// ValidateDiscountCoupon is the resolver for the validateDiscountCoupon field.
func (r *queryResolver) ValidateDiscountCoupon(ctx context.Context, input model.ValidateDiscountCouponInput) (*model.ValidateDiscountCouponResponse, error) {
	// Llamar al caso de uso
	validation, err := r.paymentInfraService.ValidateDiscountCoupon(ctx, input.CouponCode, input.RackID, input.TraceID)
	if err != nil {
		return nil, fmt.Errorf("failed to validate discount coupon: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToValidateCouponResponse(validation), nil
}

// GetPurchaseOrderByPo is the resolver for the getPurchaseOrderByPo field.
func (r *queryResolver) GetPurchaseOrderByPo(ctx context.Context, input model.GetPurchaseOrderByPoInput) (*model.PurchaseOrderResponse, error) {
	// Llamar al caso de uso
	orderData, err := r.paymentInfraService.GetPurchaseOrderByPo(ctx, input.PurchaseOrder, input.TraceID)
	if err != nil {
		return nil, fmt.Errorf("failed to get purchase order: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToPurchaseOrderDataResponse(orderData), nil
}

// CheckBookingStatus is the resolver for the checkBookingStatus field.
func (r *queryResolver) CheckBookingStatus(ctx context.Context, input model.CheckBookingStatusInput) (*model.CheckBookingStatusResponse, error) {
	// Llamar al caso de uso
	bookingStatus, err := r.paymentInfraService.CheckBookingStatus(ctx, input.ServiceName, input.CurrentCode)
	if err != nil {
		return nil, fmt.Errorf("failed to check booking status: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToBookingStatusResponse(bookingStatus), nil
}

// ExecuteOpen is the resolver for the executeOpen field.
func (r *subscriptionResolver) ExecuteOpen(ctx context.Context, input model.ExecuteOpenInput) (<-chan *model.ExecuteOpenResponse, error) {
	// Log de entrada
	fmt.Printf("🔷 GraphQL Subscription - ExecuteOpen REQUEST: serviceName=%s, currentCode=%s\n",
		input.ServiceName, input.CurrentCode)

	// Obtener el canal del servicio que emite los 3 estados progresivamente
	domainChan, err := r.paymentInfraService.ExecuteOpenStream(ctx, input.ServiceName, input.CurrentCode)
	if err != nil {
		fmt.Printf("❌ GraphQL Subscription - ExecuteOpen FAILED to start: %v\n", err)
		return nil, fmt.Errorf("failed to execute open: %w", err)
	}

	// Crear canal de salida para GraphQL con buffer suficiente para los 3 mensajes
	outputChan := make(chan *model.ExecuteOpenResponse, 5)

	// Goroutine para transformar y reenviar los mensajes del dominio a GraphQL
	go func() {
		defer func() {
			fmt.Printf("🔒 GraphQL Subscription - Closing output channel\n")
			close(outputChan)
		}()

		messageCount := 0
		var lastMessage *model.ExecuteOpenResponse

		for domainResult := range domainChan {
			messageCount++

			// Log del estado recibido
			fmt.Printf("📥 GraphQL Subscription - Message %d: openStatus=%v, message=%s\n",
				messageCount, domainResult.OpenStatus, domainResult.Message)

			// Mapear de dominio a GraphQL
			graphQLResponse := r.mapper.ToExecuteOpenResponse(domainResult)
			lastMessage = graphQLResponse

			// Enviar al frontend de forma no bloqueante con timeout
			select {
			case outputChan <- graphQLResponse:
				fmt.Printf("✅ GraphQL Subscription - Sent message %d to frontend: status=%v\n",
					messageCount, graphQLResponse.OpenStatus)
			case <-ctx.Done():
				fmt.Printf("⚠️ GraphQL Subscription - Context cancelled after %d messages\n", messageCount)
				return
			}

			// Log si es un estado terminal pero NO salimos, esperamos a que el canal se vacíe
			if domainResult.OpenStatus == "OPEN_STATUS_SUCCESS" || domainResult.OpenStatus == "OPEN_STATUS_ERROR" {
				fmt.Printf("🏁 GraphQL Subscription - Terminal status sent (%v), waiting for channel drain\n", domainResult.OpenStatus)
			}
		}

		// El canal domainChan se cerró (ya se enviaron todos los mensajes)
		fmt.Printf("✅ GraphQL Subscription - ExecuteOpen completed with %d messages, last status: %v\n",
			messageCount, lastMessage.OpenStatus)

		// Pequeño delay para asegurar que el último mensaje se procese
		time.Sleep(100 * time.Millisecond)
	}()

	return outputChan, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
